package com.mitewater.blog.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("T_JBLOG_CLASSSIFICATION", "ID", CLASSSIFICATION.class);
		arp.addMapping("T_JBLOG_MSG", "ID", MSG.class);
		arp.addMapping("T_JBLOG_USER", "ID", USER.class);
		arp.addMapping("T_JBLOG_VIEW", "ID", VIEW.class);
		arp.addMapping("T_JBLOG_VISIT_LOG", "ID", VisitLog.class);
	}
}

