package com.mitewater.blog.model;

import com.mitewater.blog.model.base.BaseCLASSSIFICATION;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CLASSSIFICATION extends BaseCLASSSIFICATION<CLASSSIFICATION> {
	public static final CLASSSIFICATION dao = new CLASSSIFICATION();
}
