package com.mitewater.blog.model;

import com.mitewater.blog.model.base.BaseMSG;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MSG extends BaseMSG<MSG> {
	public static final MSG dao = new MSG();
}
