package com.mitewater.blog.model;

import com.mitewater.blog.model.base.BaseUSER;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class USER extends BaseUSER<USER> {
	public static final USER dao = new USER();
}
