package com.mitewater.blog.model;

import com.mitewater.blog.model.base.BaseVIEW;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VIEW extends BaseVIEW<VIEW> {
	public static final VIEW dao = new VIEW();
}
