package com.mitewater.blog.model;

import com.mitewater.blog.model.base.BaseVisitLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VisitLog extends BaseVisitLog<VisitLog> {
	public static final VisitLog dao = new VisitLog();
}
