package com.mitewater.blog.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCLASSSIFICATION<M extends BaseCLASSSIFICATION<M>> extends Model<M> implements IBean {

	public void setID(java.lang.String ID) {
		set("ID", ID);
	}

	public java.lang.String getID() {
		return get("ID");
	}

	public void setClssName(java.lang.String clssName) {
		set("CLSS_NAME", clssName);
	}

	public java.lang.String getClssName() {
		return get("CLSS_NAME");
	}

	public void setPClassId(java.lang.String pClassId) {
		set("P_CLASS_ID", pClassId);
	}

	public java.lang.String getPClassId() {
		return get("P_CLASS_ID");
	}

	public void setShowLevel(java.lang.String showLevel) {
		set("SHOW_LEVEL", showLevel);
	}

	public java.lang.String getShowLevel() {
		return get("SHOW_LEVEL");
	}

}
