package com.mitewater.blog.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUSER<M extends BaseUSER<M>> extends Model<M> implements IBean {

	public void setID(java.lang.String ID) {
		set("ID", ID);
	}

	public java.lang.String getID() {
		return get("ID");
	}

	public void setUserName(java.lang.String userName) {
		set("USER_NAME", userName);
	}

	public java.lang.String getUserName() {
		return get("USER_NAME");
	}

	public void setUserPwd(java.lang.String userPwd) {
		set("USER_PWD", userPwd);
	}

	public java.lang.String getUserPwd() {
		return get("USER_PWD");
	}

	public void setUserAliens(java.lang.String userAliens) {
		set("USER_ALIENS", userAliens);
	}

	public java.lang.String getUserAliens() {
		return get("USER_ALIENS");
	}

	public void setUserType(java.lang.String userType) {
		set("USER_TYPE", userType);
	}

	public java.lang.String getUserType() {
		return get("USER_TYPE");
	}

}
