package com.mitewater.blog.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseVisitLog<M extends BaseVisitLog<M>> extends Model<M> implements IBean {

	public void setID(java.lang.String ID) {
		set("ID", ID);
	}

	public java.lang.String getID() {
		return get("ID");
	}

	public void setIP(java.lang.String IP) {
		set("IP", IP);
	}

	public java.lang.String getIP() {
		return get("IP");
	}

	public void setVisitTime(java.util.Date visitTime) {
		set("VISIT_TIME", visitTime);
	}

	public java.util.Date getVisitTime() {
		return get("VISIT_TIME");
	}

	public void setVisitType(java.lang.String visitType) {
		set("VISIT_TYPE", visitType);
	}

	public java.lang.String getVisitType() {
		return get("VISIT_TYPE");
	}

}
